### ISSUE TITLE
File not found on README tutorial URL

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-debugger-idea-sample#1]
http://googlecloudplatform.github.io/google-cloud-intellij/tutorial.html

**Comment by elharo** [comment]
Pointed to the one on devsite for the moment, but not sure what happened to the one on github pages.

**Comment by elharo** [comment]
Possibly the repo rename broke this:

https://help.github.com/articles/renaming-a-repository/

"When you rename a repository, all existing information, _with the exception of Project Pages URLs_, is automatically redirected to the new name"

Hopefully I can still find the old pages.

**Comment by elharo** [comment]
Do we have a way to open a ticket with Github? I can't figure out where our gh_pages branch went and how to get it back. I don't seem to have a local copy on any of my machines.

**Comment by elharo** [comment]
Found a local copy. Whew, but it's still disturbing that an entire branch can be deleted from Github, possibly as a die effect of other actions, with no record whatsoever.

**Comment by elharo** [comment]
fixed
